### ISSUE TITLE
好像又不能用了，求大大幫助

### ISSUE THREAD

**Issue by CLOVERsquare** [johnson18404/BahaForumPreviewer#2]

**Comment by johnson18404** [comment]
chrome v73之後對一些API進行限制，我已在今天針對此問題推送更新了。
檢查一下你是否有收到目前最新版本2.3，如果沒有的話試著將chrome完全關閉再重啟應該就會自動更新了。
![](https://i.imgur.com/qVqwJJ4.jpg)

**Comment by CLOVERsquare** [comment]
我愛你，已可正常使用，感謝大大
